version: '3.1'

services: 
    chatgpt: 
    image: chatgpt 
    container_name: chatgpt 
    restart: always 
    ports: - 8888:8888 
    environment: 
      - PORT=8888 
    volumes: 
      - ./chatgpt/:/app 
    command: bash run.sh 
