version: '3'

services:
  OpenAI-ChatGPT:
    image: openai/gpt-2
    ports:
      - "8080:8080"
    volumes:
      - ./:/models
    environment:
      - DOCKER=1
      - PYTHONPATH=/models
    command: python3 /models/server.py
