version: '3.7'

services:
  chat: 
    image: ubuntu:18.04
    networks:
      - ConversationalNet
    container_name: chatgpt
    volumes:
      - ./data:/data
    entrypoint:
      "python"
      "-m"
      "chatbot.main"
      "--model_name"
      "chatgpt"
      "--model_config"
      "/data/model_config.json"
      "--data_direct"
      "/data/data.json"
networks:
  ConversationalNet:
